version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: quantdesk-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-quantdesk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-quantdesk}
      POSTGRES_DB: ${POSTGRES_DB:-quantdesk}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: quantdesk-redis
    ports:
      - "6379:6379"

  backend:
    image: quantdeskacrswe9918.azurecr.io/quantdesk-api:latest
    container_name: quantdesk-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}

  frontend:
    image: quantdeskacrswe9918.azurecr.io/quantdesk-ui:latest
    container_name: quantdesk-ui
    ports:
      - "80:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL}


volumes:
  postgres_data:

